# Auto-generated list of best commands from jobs-feature-noise-*

python main.py --dataset_name Cora --model FISF --feature_missing_rate 0 --feature_missing_type uniform --feature_noise_rate 0.1 --hidden_channels 128 --num_layers 2 --label_max_hops 1 --label_temperature 0.25 --lp_alpha 0.99 --goodie_lamb 1 --fisf_alpha 0.7 --fisf_beta 0.9 --fisf_gamma 50 --fisf_mask_type uniform --n_runs 25 --epochs 1000 --early_stopping True --patience 100 --disable_tqdm True --results_csv experiments/Cora/FISF/FEATURE_NOISE0.1_SEARCH.csv
python main.py --dataset_name Cora --model GCN --label_noise_type uniform --label_noise_rate 0.0 --feature_missing_type uniform --feature_missing_rate 0.0 --feature_noise_rate 0.1 --hidden_channels 64 --num_layers 2 --lr 0.01 --weight_decay 0.0005 --dropout 0.5 --epochs 1000 --n_runs 25 --results_csv experiments/Cora/GCN/FEATURE_NOISE0.1_SEARCH.csv
python main.py --dataset_name Cora --model GCNmf --label_noise_type uniform --label_noise_rate 0.0 --feature_missing_type uniform --feature_missing_rate 0.0 --feature_noise_rate 0.1 --hidden_channels 32 --num_layers 2 --lr 0.01 --weight_decay 0.0005 --dropout 0.5 --epochs 1000 --n_runs 25 --results_csv experiments/Cora/GCNmf/FEATURE_NOISE0.1_SEARCH.csv
python main.py --dataset_name Cora --model Goodie --label_noise_type uniform --label_noise_rate 0.0 --feature_missing_type uniform --feature_missing_rate 0.0 --feature_noise_rate 0.1 --hidden_channels 64 --num_layers 1 --lr 0.01 --weight_decay 0.0005 --dropout 0.5 --epochs 1000 --lp_alpha 0.99 --goodie_lamb 0.01 --n_runs 25 --results_csv experiments/Cora/Goodie/FEATURE_NOISE0.1_SEARCH.csv
python main.py --dataset_name Cora --model H2GCN --label_noise_type uniform --label_noise_rate 0.0 --feature_missing_type uniform --feature_missing_rate 0.0 --feature_noise_rate 0.1 --hidden_channels 32 --num_layers 2 --lr 0.01 --weight_decay 0.0005 --dropout 0.5 --epochs 1000 --n_runs 25 --results_csv experiments/Cora/H2GCN/FEATURE_NOISE0.1_SEARCH.csv
python main.py --dataset_name Cora --model LP --label_noise_type uniform --label_noise_rate 0.0 --feature_missing_type uniform --feature_missing_rate 0.0 --feature_noise_rate 0.1 --hidden_channels 32 --num_layers 1 --lr 0.01 --weight_decay 0.0005 --dropout 0.5 --epochs 1000 --lp_alpha_lp 0.9 --n_runs 25 --results_csv experiments/Cora/LP/FEATURE_NOISE0.1_SEARCH.csv
python main.py --dataset_name Cora --model LRGCN --label_noise_type uniform --label_noise_rate 0.0 --feature_missing_type uniform --feature_missing_rate 0.0 --feature_noise_rate 0.1 --hidden_channels 128 --num_layers 1 --lr 0.01 --weight_decay 0.0005 --dropout 0.5 --epochs 1000 --label_max_hops 2 --label_temperature 0.125 --n_runs 25 --results_csv experiments/Cora/LRGCN/FEATURE_NOISE0.1_SEARCH.csv
python main.py --dataset_name Cora --model MLP --label_noise_type uniform --label_noise_rate 0.0 --feature_missing_type uniform --feature_missing_rate 0.0 --feature_noise_rate 0.1 --hidden_channels 128 --num_layers 1 --lr 0.01 --weight_decay 0.0005 --dropout 0.5 --epochs 1000 --n_runs 25 --results_csv experiments/Cora/MLP/FEATURE_NOISE0.1_SEARCH.csv
python main.py --dataset_name Cora --model PaGNN --label_noise_type uniform --label_noise_rate 0.0 --feature_missing_type uniform --feature_missing_rate 0.0 --feature_noise_rate 0.1 --hidden_channels 64 --num_layers 1 --lr 0.01 --weight_decay 0.0005 --dropout 0.5 --epochs 1000 --n_runs 25 --results_csv experiments/Cora/PaGNN/FEATURE_NOISE0.1_SEARCH.csv

python main.py --dataset_name Texas --model FISF --feature_missing_rate 0 --feature_missing_type uniform --feature_noise_rate 0.1 --hidden_channels 128 --num_layers 2 --label_max_hops 1 --label_temperature 0.25 --lp_alpha 0.99 --goodie_lamb 1 --fisf_alpha 0.5 --fisf_beta 0.5 --fisf_gamma 50 --fisf_mask_type uniform --n_runs 25 --epochs 1000 --early_stopping True --patience 100 --disable_tqdm True --results_csv experiments/Texas/FISF/FEATURE_NOISE0.1_SEARCH.csv
python main.py --dataset_name Texas --model GCN --label_noise_type uniform --label_noise_rate 0.0 --feature_missing_type uniform --feature_missing_rate 0.0 --feature_noise_rate 0.1 --hidden_channels 128 --num_layers 2 --lr 0.01 --weight_decay 0.0005 --dropout 0.5 --epochs 1000 --n_runs 100 --results_csv experiments/Texas/GCN/FEATURE_NOISE0.1_SEARCH.csv
python main.py --dataset_name Texas --model GCNmf --label_noise_type uniform --label_noise_rate 0.0 --feature_missing_type uniform --feature_missing_rate 0.0 --feature_noise_rate 0.1 --hidden_channels 128 --num_layers 2 --lr 0.01 --weight_decay 0.0005 --dropout 0.5 --epochs 1000 --n_runs 100 --results_csv experiments/Texas/GCNmf/FEATURE_NOISE0.1_SEARCH.csv
python main.py --dataset_name Texas --model Goodie --label_noise_type uniform --label_noise_rate 0.0 --feature_missing_type uniform --feature_missing_rate 0.0 --feature_noise_rate 0.1 --hidden_channels 128 --num_layers 1 --lr 0.01 --weight_decay 0.0005 --dropout 0.5 --epochs 1000 --lp_alpha 0.9 --goodie_lamb 0.001 --n_runs 100 --results_csv experiments/Texas/Goodie/FEATURE_NOISE0.1_SEARCH.csv
python main.py --dataset_name Texas --model H2GCN --label_noise_type uniform --label_noise_rate 0.0 --feature_missing_type uniform --feature_missing_rate 0.0 --feature_noise_rate 0.1 --hidden_channels 128 --num_layers 1 --lr 0.01 --weight_decay 0.0005 --dropout 0.5 --epochs 1000 --n_runs 100 --results_csv experiments/Texas/H2GCN/FEATURE_NOISE0.1_SEARCH.csv
python main.py --dataset_name Texas --model LP --label_noise_type uniform --label_noise_rate 0.0 --feature_missing_type uniform --feature_missing_rate 0.0 --feature_noise_rate 0.1 --hidden_channels 32 --num_layers 1 --lr 0.01 --weight_decay 0.0005 --dropout 0.5 --epochs 1000 --lp_alpha_lp 0.9 --n_runs 100 --results_csv experiments/Texas/LP/FEATURE_NOISE0.1_SEARCH.csv
python main.py --dataset_name Texas --model LRGCN --label_noise_type uniform --label_noise_rate 0.0 --feature_missing_type uniform --feature_missing_rate 0.0 --feature_noise_rate 0.1 --hidden_channels 128 --num_layers 1 --lr 0.01 --weight_decay 0.0005 --dropout 0.5 --epochs 1000 --label_max_hops 1 --label_temperature 0.5 --n_runs 100 --results_csv experiments/Texas/LRGCN/FEATURE_NOISE0.1_SEARCH.csv
python main.py --dataset_name Texas --model MLP --label_noise_type uniform --label_noise_rate 0.0 --feature_missing_type uniform --feature_missing_rate 0.0 --feature_noise_rate 0.1 --hidden_channels 128 --num_layers 1 --lr 0.01 --weight_decay 0.0005 --dropout 0.5 --epochs 1000 --n_runs 100 --results_csv experiments/Texas/MLP/FEATURE_NOISE0.1_SEARCH.csv
python main.py --dataset_name Texas --model PaGNN --label_noise_type uniform --label_noise_rate 0.0 --feature_missing_type uniform --feature_missing_rate 0.0 --feature_noise_rate 0.1 --hidden_channels 128 --num_layers 1 --lr 0.01 --weight_decay 0.0005 --dropout 0.5 --epochs 1000 --n_runs 100 --results_csv experiments/Texas/PaGNN/FEATURE_NOISE0.1_SEARCH.csv

python main.py --dataset_name Cora --model FISF --feature_missing_rate 0 --feature_missing_type uniform --feature_noise_rate 0.3 --hidden_channels 128 --num_layers 2 --label_max_hops 1 --label_temperature 0.25 --lp_alpha 0.99 --goodie_lamb 1 --fisf_alpha 0.7 --fisf_beta 0.9 --fisf_gamma 50 --fisf_mask_type uniform --n_runs 25 --epochs 1000 --early_stopping True --patience 100 --disable_tqdm True --results_csv experiments/Cora/FISF/FEATURE_NOISE0.3_SEARCH.csv
python main.py --dataset_name Cora --model GCN --label_noise_type uniform --label_noise_rate 0.0 --feature_missing_type uniform --feature_missing_rate 0.0 --feature_noise_rate 0.3 --hidden_channels 128 --num_layers 2 --lr 0.01 --weight_decay 0.0005 --dropout 0.5 --epochs 1000 --n_runs 25 --results_csv experiments/Cora/GCN/FEATURE_NOISE0.3_SEARCH.csv
python main.py --dataset_name Cora --model GCNmf --label_noise_type uniform --label_noise_rate 0.0 --feature_missing_type uniform --feature_missing_rate 0.0 --feature_noise_rate 0.3 --hidden_channels 32 --num_layers 2 --lr 0.01 --weight_decay 0.0005 --dropout 0.5 --epochs 1000 --n_runs 25 --results_csv experiments/Cora/GCNmf/FEATURE_NOISE0.3_SEARCH.csv
python main.py --dataset_name Cora --model Goodie --label_noise_type uniform --label_noise_rate 0.0 --feature_missing_type uniform --feature_missing_rate 0.0 --feature_noise_rate 0.3 --hidden_channels 64 --num_layers 1 --lr 0.01 --weight_decay 0.0005 --dropout 0.5 --epochs 1000 --lp_alpha 0.9 --goodie_lamb 0.001 --n_runs 25 --results_csv experiments/Cora/Goodie/FEATURE_NOISE0.3_SEARCH.csv
python main.py --dataset_name Cora --model H2GCN --label_noise_type uniform --label_noise_rate 0.0 --feature_missing_type uniform --feature_missing_rate 0.0 --feature_noise_rate 0.3 --hidden_channels 64 --num_layers 2 --lr 0.01 --weight_decay 0.0005 --dropout 0.5 --epochs 1000 --n_runs 25 --results_csv experiments/Cora/H2GCN/FEATURE_NOISE0.3_SEARCH.csv
python main.py --dataset_name Cora --model LP --label_noise_type uniform --label_noise_rate 0.0 --feature_missing_type uniform --feature_missing_rate 0.0 --feature_noise_rate 0.3 --hidden_channels 32 --num_layers 1 --lr 0.01 --weight_decay 0.0005 --dropout 0.5 --epochs 1000 --lp_alpha_lp 0.9 --n_runs 25 --results_csv experiments/Cora/LP/FEATURE_NOISE0.3_SEARCH.csv
python main.py --dataset_name Cora --model LRGCN --label_noise_type uniform --label_noise_rate 0.0 --feature_missing_type uniform --feature_missing_rate 0.0 --feature_noise_rate 0.3 --hidden_channels 128 --num_layers 1 --lr 0.01 --weight_decay 0.0005 --dropout 0.5 --epochs 1000 --label_max_hops 2 --label_temperature 0.25 --n_runs 25 --results_csv experiments/Cora/LRGCN/FEATURE_NOISE0.3_SEARCH.csv
python main.py --dataset_name Cora --model MLP --label_noise_type uniform --label_noise_rate 0.0 --feature_missing_type uniform --feature_missing_rate 0.0 --feature_noise_rate 0.3 --hidden_channels 128 --num_layers 1 --lr 0.01 --weight_decay 0.0005 --dropout 0.5 --epochs 1000 --n_runs 25 --results_csv experiments/Cora/MLP/FEATURE_NOISE0.3_SEARCH.csv
python main.py --dataset_name Cora --model PaGNN --label_noise_type uniform --label_noise_rate 0.0 --feature_missing_type uniform --feature_missing_rate 0.0 --feature_noise_rate 0.3 --hidden_channels 128 --num_layers 1 --lr 0.01 --weight_decay 0.0005 --dropout 0.5 --epochs 1000 --n_runs 25 --results_csv experiments/Cora/PaGNN/FEATURE_NOISE0.3_SEARCH.csv

python main.py --dataset_name Texas --model FISF --feature_missing_rate 0 --feature_missing_type uniform --feature_noise_rate 0.3 --hidden_channels 128 --num_layers 2 --label_max_hops 1 --label_temperature 0.25 --lp_alpha 0.99 --goodie_lamb 1 --fisf_alpha 0.5 --fisf_beta 0.5 --fisf_gamma 50 --fisf_mask_type uniform --n_runs 25 --epochs 1000 --early_stopping True --patience 100 --disable_tqdm True --results_csv experiments/Texas/FISF/FEATURE_NOISE0.3_SEARCH.csv
python main.py --dataset_name Texas --model GCN --label_noise_type uniform --label_noise_rate 0.0 --feature_missing_type uniform --feature_missing_rate 0.0 --feature_noise_rate 0.3 --hidden_channels 128 --num_layers 2 --lr 0.01 --weight_decay 0.0005 --dropout 0.5 --epochs 1000 --n_runs 100 --results_csv experiments/Texas/GCN/FEATURE_NOISE0.3_SEARCH.csv
python main.py --dataset_name Texas --model GCNmf --label_noise_type uniform --label_noise_rate 0.0 --feature_missing_type uniform --feature_missing_rate 0.0 --feature_noise_rate 0.3 --hidden_channels 128 --num_layers 1 --lr 0.01 --weight_decay 0.0005 --dropout 0.5 --epochs 1000 --n_runs 100 --results_csv experiments/Texas/GCNmf/FEATURE_NOISE0.3_SEARCH.csv
python main.py --dataset_name Texas --model Goodie --label_noise_type uniform --label_noise_rate 0.0 --feature_missing_type uniform --feature_missing_rate 0.0 --feature_noise_rate 0.3 --hidden_channels 64 --num_layers 1 --lr 0.01 --weight_decay 0.0005 --dropout 0.5 --epochs 1000 --lp_alpha 0.99 --goodie_lamb 0.001 --n_runs 100 --results_csv experiments/Texas/Goodie/FEATURE_NOISE0.3_SEARCH.csv
python main.py --dataset_name Texas --model H2GCN --label_noise_type uniform --label_noise_rate 0.0 --feature_missing_type uniform --feature_missing_rate 0.0 --feature_noise_rate 0.3 --hidden_channels 128 --num_layers 1 --lr 0.01 --weight_decay 0.0005 --dropout 0.5 --epochs 1000 --n_runs 100 --results_csv experiments/Texas/H2GCN/FEATURE_NOISE0.3_SEARCH.csv
python main.py --dataset_name Texas --model LP --label_noise_type uniform --label_noise_rate 0.0 --feature_missing_type uniform --feature_missing_rate 0.0 --feature_noise_rate 0.3 --hidden_channels 32 --num_layers 1 --lr 0.01 --weight_decay 0.0005 --dropout 0.5 --epochs 1000 --lp_alpha_lp 0.9 --n_runs 100 --results_csv experiments/Texas/LP/FEATURE_NOISE0.3_SEARCH.csv
python main.py --dataset_name Texas --model LRGCN --label_noise_type uniform --label_noise_rate 0.0 --feature_missing_type uniform --feature_missing_rate 0.0 --feature_noise_rate 0.3 --hidden_channels 128 --num_layers 2 --lr 0.01 --weight_decay 0.0005 --dropout 0.5 --epochs 1000 --label_max_hops 1 --label_temperature 0.5 --n_runs 100 --results_csv experiments/Texas/LRGCN/FEATURE_NOISE0.3_SEARCH.csv
python main.py --dataset_name Texas --model MLP --label_noise_type uniform --label_noise_rate 0.0 --feature_missing_type uniform --feature_missing_rate 0.0 --feature_noise_rate 0.3 --hidden_channels 128 --num_layers 1 --lr 0.01 --weight_decay 0.0005 --dropout 0.5 --epochs 1000 --n_runs 100 --results_csv experiments/Texas/MLP/FEATURE_NOISE0.3_SEARCH.csv
python main.py --dataset_name Texas --model PaGNN --label_noise_type uniform --label_noise_rate 0.0 --feature_missing_type uniform --feature_missing_rate 0.0 --feature_noise_rate 0.3 --hidden_channels 128 --num_layers 1 --lr 0.01 --weight_decay 0.0005 --dropout 0.5 --epochs 1000 --n_runs 100 --results_csv experiments/Texas/PaGNN/FEATURE_NOISE0.3_SEARCH.csv

python main.py --dataset_name Cora --model FISF --feature_missing_rate 0 --feature_missing_type uniform --feature_noise_rate 0.5 --hidden_channels 128 --num_layers 2 --label_max_hops 1 --label_temperature 0.25 --lp_alpha 0.99 --goodie_lamb 1 --fisf_alpha 0.7 --fisf_beta 0.9 --fisf_gamma 50 --fisf_mask_type uniform --n_runs 25 --epochs 1000 --early_stopping True --patience 100 --disable_tqdm True --results_csv experiments/Cora/FISF/FEATURE_NOISE0.5_SEARCH.csv
python main.py --dataset_name Cora --model GCN --label_noise_type uniform --label_noise_rate 0.0 --feature_missing_type uniform --feature_missing_rate 0.0 --feature_noise_rate 0.5 --hidden_channels 128 --num_layers 2 --lr 0.01 --weight_decay 0.0005 --dropout 0.5 --epochs 1000 --n_runs 25 --results_csv experiments/Cora/GCN/FEATURE_NOISE0.5_SEARCH.csv
python main.py --dataset_name Cora --model GCNmf --label_noise_type uniform --label_noise_rate 0.0 --feature_missing_type uniform --feature_missing_rate 0.0 --feature_noise_rate 0.5 --hidden_channels 64 --num_layers 1 --lr 0.01 --weight_decay 0.0005 --dropout 0.5 --epochs 1000 --n_runs 25 --results_csv experiments/Cora/GCNmf/FEATURE_NOISE0.5_SEARCH.csv
python main.py --dataset_name Cora --model Goodie --label_noise_type uniform --label_noise_rate 0.0 --feature_missing_type uniform --feature_missing_rate 0.0 --feature_noise_rate 0.5 --hidden_channels 128 --num_layers 1 --lr 0.01 --weight_decay 0.0005 --dropout 0.5 --epochs 1000 --lp_alpha 0.9 --goodie_lamb 0.001 --n_runs 25 --results_csv experiments/Cora/Goodie/FEATURE_NOISE0.5_SEARCH.csv
python main.py --dataset_name Cora --model H2GCN --label_noise_type uniform --label_noise_rate 0.0 --feature_missing_type uniform --feature_missing_rate 0.0 --feature_noise_rate 0.5 --hidden_channels 32 --num_layers 2 --lr 0.01 --weight_decay 0.0005 --dropout 0.5 --epochs 1000 --n_runs 25 --results_csv experiments/Cora/H2GCN/FEATURE_NOISE0.5_SEARCH.csv
python main.py --dataset_name Cora --model LP --label_noise_type uniform --label_noise_rate 0.0 --feature_missing_type uniform --feature_missing_rate 0.0 --feature_noise_rate 0.5 --hidden_channels 32 --num_layers 1 --lr 0.01 --weight_decay 0.0005 --dropout 0.5 --epochs 1000 --lp_alpha_lp 0.9 --n_runs 25 --results_csv experiments/Cora/LP/FEATURE_NOISE0.5_SEARCH.csv
python main.py --dataset_name Cora --model LRGCN --label_noise_type uniform --label_noise_rate 0.0 --feature_missing_type uniform --feature_missing_rate 0.0 --feature_noise_rate 0.5 --hidden_channels 64 --num_layers 1 --lr 0.01 --weight_decay 0.0005 --dropout 0.5 --epochs 1000 --label_max_hops 2 --label_temperature 0.125 --n_runs 25 --results_csv experiments/Cora/LRGCN/FEATURE_NOISE0.5_SEARCH.csv
python main.py --dataset_name Cora --model MLP --label_noise_type uniform --label_noise_rate 0.0 --feature_missing_type uniform --feature_missing_rate 0.0 --feature_noise_rate 0.5 --hidden_channels 64 --num_layers 1 --lr 0.01 --weight_decay 0.0005 --dropout 0.5 --epochs 1000 --n_runs 25 --results_csv experiments/Cora/MLP/FEATURE_NOISE0.5_SEARCH.csv
python main.py --dataset_name Cora --model PaGNN --label_noise_type uniform --label_noise_rate 0.0 --feature_missing_type uniform --feature_missing_rate 0.0 --feature_noise_rate 0.5 --hidden_channels 64 --num_layers 1 --lr 0.01 --weight_decay 0.0005 --dropout 0.5 --epochs 1000 --n_runs 25 --results_csv experiments/Cora/PaGNN/FEATURE_NOISE0.5_SEARCH.csv

python main.py --dataset_name Texas --model FISF --feature_missing_rate 0 --feature_missing_type uniform --feature_noise_rate 0.5 --hidden_channels 128 --num_layers 2 --label_max_hops 1 --label_temperature 0.25 --lp_alpha 0.99 --goodie_lamb 1 --fisf_alpha 0.5 --fisf_beta 0.5 --fisf_gamma 50 --fisf_mask_type uniform --n_runs 25 --epochs 1000 --early_stopping True --patience 100 --disable_tqdm True --results_csv experiments/Texas/FISF/FEATURE_NOISE0.5_SEARCH.csv
python main.py --dataset_name Texas --model GCN --label_noise_type uniform --label_noise_rate 0.0 --feature_missing_type uniform --feature_missing_rate 0.0 --feature_noise_rate 0.5 --hidden_channels 128 --num_layers 2 --lr 0.01 --weight_decay 0.0005 --dropout 0.5 --epochs 1000 --n_runs 100 --results_csv experiments/Texas/GCN/FEATURE_NOISE0.5_SEARCH.csv
python main.py --dataset_name Texas --model GCNmf --label_noise_type uniform --label_noise_rate 0.0 --feature_missing_type uniform --feature_missing_rate 0.0 --feature_noise_rate 0.5 --hidden_channels 128 --num_layers 1 --lr 0.01 --weight_decay 0.0005 --dropout 0.5 --epochs 1000 --n_runs 100 --results_csv experiments/Texas/GCNmf/FEATURE_NOISE0.5_SEARCH.csv
python main.py --dataset_name Texas --model Goodie --label_noise_type uniform --label_noise_rate 0.0 --feature_missing_type uniform --feature_missing_rate 0.0 --feature_noise_rate 0.5 --hidden_channels 64 --num_layers 1 --lr 0.01 --weight_decay 0.0005 --dropout 0.5 --epochs 1000 --lp_alpha 0.999 --goodie_lamb 0.001 --n_runs 100 --results_csv experiments/Texas/Goodie/FEATURE_NOISE0.5_SEARCH.csv
python main.py --dataset_name Texas --model H2GCN --label_noise_type uniform --label_noise_rate 0.0 --feature_missing_type uniform --feature_missing_rate 0.0 --feature_noise_rate 0.5 --hidden_channels 128 --num_layers 2 --lr 0.01 --weight_decay 0.0005 --dropout 0.5 --epochs 1000 --n_runs 100 --results_csv experiments/Texas/H2GCN/FEATURE_NOISE0.5_SEARCH.csv
python main.py --dataset_name Texas --model LP --label_noise_type uniform --label_noise_rate 0.0 --feature_missing_type uniform --feature_missing_rate 0.0 --feature_noise_rate 0.5 --hidden_channels 32 --num_layers 1 --lr 0.01 --weight_decay 0.0005 --dropout 0.5 --epochs 1000 --lp_alpha_lp 0.9 --n_runs 100 --results_csv experiments/Texas/LP/FEATURE_NOISE0.5_SEARCH.csv
python main.py --dataset_name Texas --model LRGCN --label_noise_type uniform --label_noise_rate 0.0 --feature_missing_type uniform --feature_missing_rate 0.0 --feature_noise_rate 0.5 --hidden_channels 128 --num_layers 1 --lr 0.01 --weight_decay 0.0005 --dropout 0.5 --epochs 1000 --label_max_hops 1 --label_temperature 0.5 --n_runs 100 --results_csv experiments/Texas/LRGCN/FEATURE_NOISE0.5_SEARCH.csv
python main.py --dataset_name Texas --model MLP --label_noise_type uniform --label_noise_rate 0.0 --feature_missing_type uniform --feature_missing_rate 0.0 --feature_noise_rate 0.5 --hidden_channels 128 --num_layers 1 --lr 0.01 --weight_decay 0.0005 --dropout 0.5 --epochs 1000 --n_runs 100 --results_csv experiments/Texas/MLP/FEATURE_NOISE0.5_SEARCH.csv
python main.py --dataset_name Texas --model PaGNN --label_noise_type uniform --label_noise_rate 0.0 --feature_missing_type uniform --feature_missing_rate 0.0 --feature_noise_rate 0.5 --hidden_channels 128 --num_layers 1 --lr 0.01 --weight_decay 0.0005 --dropout 0.5 --epochs 1000 --n_runs 100 --results_csv experiments/Texas/PaGNN/FEATURE_NOISE0.5_SEARCH.csv

python main.py --dataset_name Cora --model FISF --feature_missing_rate 0 --feature_missing_type uniform --feature_noise_rate 0.7 --hidden_channels 128 --num_layers 2 --label_max_hops 1 --label_temperature 0.25 --lp_alpha 0.99 --goodie_lamb 1 --fisf_alpha 0.7 --fisf_beta 0.9 --fisf_gamma 50 --fisf_mask_type uniform --n_runs 25 --epochs 1000 --early_stopping True --patience 100 --disable_tqdm True --results_csv experiments/Cora/FISF/FEATURE_NOISE0.7_SEARCH.csv
python main.py --dataset_name Cora --model GCN --label_noise_type uniform --label_noise_rate 0.0 --feature_missing_type uniform --feature_missing_rate 0.0 --feature_noise_rate 0.7 --hidden_channels 128 --num_layers 2 --lr 0.01 --weight_decay 0.0005 --dropout 0.5 --epochs 1000 --n_runs 25 --results_csv experiments/Cora/GCN/FEATURE_NOISE0.7_SEARCH.csv
python main.py --dataset_name Cora --model GCNmf --label_noise_type uniform --label_noise_rate 0.0 --feature_missing_type uniform --feature_missing_rate 0.0 --feature_noise_rate 0.7 --hidden_channels 128 --num_layers 1 --lr 0.01 --weight_decay 0.0005 --dropout 0.5 --epochs 1000 --n_runs 25 --results_csv experiments/Cora/GCNmf/FEATURE_NOISE0.7_SEARCH.csv
python main.py --dataset_name Cora --model Goodie --label_noise_type uniform --label_noise_rate 0.0 --feature_missing_type uniform --feature_missing_rate 0.0 --feature_noise_rate 0.7 --hidden_channels 64 --num_layers 1 --lr 0.01 --weight_decay 0.0005 --dropout 0.5 --epochs 1000 --lp_alpha 0.9 --goodie_lamb 0.001 --n_runs 25 --results_csv experiments/Cora/Goodie/FEATURE_NOISE0.7_SEARCH.csv
python main.py --dataset_name Cora --model H2GCN --label_noise_type uniform --label_noise_rate 0.0 --feature_missing_type uniform --feature_missing_rate 0.0 --feature_noise_rate 0.7 --hidden_channels 32 --num_layers 2 --lr 0.01 --weight_decay 0.0005 --dropout 0.5 --epochs 1000 --n_runs 25 --results_csv experiments/Cora/H2GCN/FEATURE_NOISE0.7_SEARCH.csv
python main.py --dataset_name Cora --model LP --label_noise_type uniform --label_noise_rate 0.0 --feature_missing_type uniform --feature_missing_rate 0.0 --feature_noise_rate 0.7 --hidden_channels 32 --num_layers 1 --lr 0.01 --weight_decay 0.0005 --dropout 0.5 --epochs 1000 --lp_alpha_lp 0.9 --n_runs 25 --results_csv experiments/Cora/LP/FEATURE_NOISE0.7_SEARCH.csv
python main.py --dataset_name Cora --model LRGCN --label_noise_type uniform --label_noise_rate 0.0 --feature_missing_type uniform --feature_missing_rate 0.0 --feature_noise_rate 0.7 --hidden_channels 128 --num_layers 2 --lr 0.01 --weight_decay 0.0005 --dropout 0.5 --epochs 1000 --label_max_hops 2 --label_temperature 0.125 --n_runs 25 --results_csv experiments/Cora/LRGCN/FEATURE_NOISE0.7_SEARCH.csv
python main.py --dataset_name Cora --model MLP --label_noise_type uniform --label_noise_rate 0.0 --feature_missing_type uniform --feature_missing_rate 0.0 --feature_noise_rate 0.7 --hidden_channels 64 --num_layers 1 --lr 0.01 --weight_decay 0.0005 --dropout 0.5 --epochs 1000 --n_runs 25 --results_csv experiments/Cora/MLP/FEATURE_NOISE0.7_SEARCH.csv
python main.py --dataset_name Cora --model PaGNN --label_noise_type uniform --label_noise_rate 0.0 --feature_missing_type uniform --feature_missing_rate 0.0 --feature_noise_rate 0.7 --hidden_channels 64 --num_layers 1 --lr 0.01 --weight_decay 0.0005 --dropout 0.5 --epochs 1000 --n_runs 25 --results_csv experiments/Cora/PaGNN/FEATURE_NOISE0.7_SEARCH.csv

python main.py --dataset_name Texas --model FISF --feature_missing_rate 0 --feature_missing_type uniform --feature_noise_rate 0.7 --hidden_channels 128 --num_layers 2 --label_max_hops 1 --label_temperature 0.25 --lp_alpha 0.99 --goodie_lamb 1 --fisf_alpha 0.5 --fisf_beta 0.5 --fisf_gamma 50 --fisf_mask_type uniform --n_runs 25 --epochs 1000 --early_stopping True --patience 100 --disable_tqdm True --results_csv experiments/Texas/FISF/FEATURE_NOISE0.7_SEARCH.csv
python main.py --dataset_name Texas --model GCN --label_noise_type uniform --label_noise_rate 0.0 --feature_missing_type uniform --feature_missing_rate 0.0 --feature_noise_rate 0.7 --hidden_channels 64 --num_layers 2 --lr 0.01 --weight_decay 0.0005 --dropout 0.5 --epochs 1000 --n_runs 100 --results_csv experiments/Texas/GCN/FEATURE_NOISE0.7_SEARCH.csv
python main.py --dataset_name Texas --model GCNmf --label_noise_type uniform --label_noise_rate 0.0 --feature_missing_type uniform --feature_missing_rate 0.0 --feature_noise_rate 0.7 --hidden_channels 128 --num_layers 2 --lr 0.01 --weight_decay 0.0005 --dropout 0.5 --epochs 1000 --n_runs 100 --results_csv experiments/Texas/GCNmf/FEATURE_NOISE0.7_SEARCH.csv
python main.py --dataset_name Texas --model Goodie --label_noise_type uniform --label_noise_rate 0.0 --feature_missing_type uniform --feature_missing_rate 0.0 --feature_noise_rate 0.7 --hidden_channels 128 --num_layers 1 --lr 0.01 --weight_decay 0.0005 --dropout 0.5 --epochs 1000 --lp_alpha 0.9 --goodie_lamb 0.001 --n_runs 100 --results_csv experiments/Texas/Goodie/FEATURE_NOISE0.7_SEARCH.csv
python main.py --dataset_name Texas --model H2GCN --label_noise_type uniform --label_noise_rate 0.0 --feature_missing_type uniform --feature_missing_rate 0.0 --feature_noise_rate 0.7 --hidden_channels 32 --num_layers 2 --lr 0.01 --weight_decay 0.0005 --dropout 0.5 --epochs 1000 --n_runs 100 --results_csv experiments/Texas/H2GCN/FEATURE_NOISE0.7_SEARCH.csv
python main.py --dataset_name Texas --model LP --label_noise_type uniform --label_noise_rate 0.0 --feature_missing_type uniform --feature_missing_rate 0.0 --feature_noise_rate 0.7 --hidden_channels 32 --num_layers 1 --lr 0.01 --weight_decay 0.0005 --dropout 0.5 --epochs 1000 --lp_alpha_lp 0.9 --n_runs 100 --results_csv experiments/Texas/LP/FEATURE_NOISE0.7_SEARCH.csv
python main.py --dataset_name Texas --model LRGCN --label_noise_type uniform --label_noise_rate 0.0 --feature_missing_type uniform --feature_missing_rate 0.0 --feature_noise_rate 0.7 --hidden_channels 128 --num_layers 2 --lr 0.01 --weight_decay 0.0005 --dropout 0.5 --epochs 1000 --label_max_hops 1 --label_temperature 0.5 --n_runs 100 --results_csv experiments/Texas/LRGCN/FEATURE_NOISE0.7_SEARCH.csv
python main.py --dataset_name Texas --model MLP --label_noise_type uniform --label_noise_rate 0.0 --feature_missing_type uniform --feature_missing_rate 0.0 --feature_noise_rate 0.7 --hidden_channels 128 --num_layers 1 --lr 0.01 --weight_decay 0.0005 --dropout 0.5 --epochs 1000 --n_runs 100 --results_csv experiments/Texas/MLP/FEATURE_NOISE0.7_SEARCH.csv
python main.py --dataset_name Texas --model PaGNN --label_noise_type uniform --label_noise_rate 0.0 --feature_missing_type uniform --feature_missing_rate 0.0 --feature_noise_rate 0.7 --hidden_channels 128 --num_layers 1 --lr 0.01 --weight_decay 0.0005 --dropout 0.5 --epochs 1000 --n_runs 100 --results_csv experiments/Texas/PaGNN/FEATURE_NOISE0.7_SEARCH.csv


python main.py --dataset_name Cora --model FISF --feature_missing_rate 0 --feature_missing_type uniform --feature_noise_rate 0.9 --hidden_channels 128 --num_layers 2 --label_max_hops 1 --label_temperature 0.25 --lp_alpha 0.99 --goodie_lamb 1 --fisf_alpha 0.7 --fisf_beta 0.9 --fisf_gamma 50 --fisf_mask_type uniform --n_runs 25 --epochs 1000 --early_stopping True --patience 100 --disable_tqdm True --results_csv experiments/Cora/FISF/FEATURE_NOISE0.9_SEARCH.csv
python main.py --dataset_name Cora --model GCN --label_noise_type uniform --label_noise_rate 0.0 --feature_missing_type uniform --feature_missing_rate 0.0 --feature_noise_rate 0.9 --hidden_channels 128 --num_layers 2 --lr 0.01 --weight_decay 0.0005 --dropout 0.5 --epochs 1000 --n_runs 25 --results_csv experiments/Cora/GCN/FEATURE_NOISE0.9_SEARCH.csv
python main.py --dataset_name Cora --model GCNmf --label_noise_type uniform --label_noise_rate 0.0 --feature_missing_type uniform --feature_missing_rate 0.0 --feature_noise_rate 0.9 --hidden_channels 128 --num_layers 2 --lr 0.01 --weight_decay 0.0005 --dropout 0.5 --epochs 1000 --n_runs 25 --results_csv experiments/Cora/GCNmf/FEATURE_NOISE0.9_SEARCH.csv
python main.py --dataset_name Cora --model Goodie --label_noise_type uniform --label_noise_rate 0.0 --feature_missing_type uniform --feature_missing_rate 0.0 --feature_noise_rate 0.9 --hidden_channels 64 --num_layers 1 --lr 0.01 --weight_decay 0.0005 --dropout 0.5 --epochs 1000 --lp_alpha 0.9 --goodie_lamb 0.01 --n_runs 25 --results_csv experiments/Cora/Goodie/FEATURE_NOISE0.9_SEARCH.csv
python main.py --dataset_name Cora --model H2GCN --label_noise_type uniform --label_noise_rate 0.0 --feature_missing_type uniform --feature_missing_rate 0.0 --feature_noise_rate 0.9 --hidden_channels 32 --num_layers 2 --lr 0.01 --weight_decay 0.0005 --dropout 0.5 --epochs 1000 --n_runs 25 --results_csv experiments/Cora/H2GCN/FEATURE_NOISE0.9_SEARCH.csv
python main.py --dataset_name Cora --model LP --label_noise_type uniform --label_noise_rate 0.0 --feature_missing_type uniform --feature_missing_rate 0.0 --feature_noise_rate 0.9 --hidden_channels 32 --num_layers 1 --lr 0.01 --weight_decay 0.0005 --dropout 0.5 --epochs 1000 --lp_alpha_lp 0.9 --n_runs 25 --results_csv experiments/Cora/LP/FEATURE_NOISE0.9_SEARCH.csv
python main.py --dataset_name Cora --model LRGCN --label_noise_type uniform --label_noise_rate 0.0 --feature_missing_type uniform --feature_missing_rate 0.0 --feature_noise_rate 0.9 --hidden_channels 128 --num_layers 1 --lr 0.01 --weight_decay 0.0005 --dropout 0.5 --epochs 1000 --label_max_hops 2 --label_temperature 0.125 --n_runs 25 --results_csv experiments/Cora/LRGCN/FEATURE_NOISE0.9_SEARCH.csv
python main.py --dataset_name Cora --model MLP --label_noise_type uniform --label_noise_rate 0.0 --feature_missing_type uniform --feature_missing_rate 0.0 --feature_noise_rate 0.9 --hidden_channels 64 --num_layers 1 --lr 0.01 --weight_decay 0.0005 --dropout 0.5 --epochs 1000 --n_runs 25 --results_csv experiments/Cora/MLP/FEATURE_NOISE0.9_SEARCH.csv
python main.py --dataset_name Cora --model PaGNN --label_noise_type uniform --label_noise_rate 0.0 --feature_missing_type uniform --feature_missing_rate 0.0 --feature_noise_rate 0.9 --hidden_channels 128 --num_layers 1 --lr 0.01 --weight_decay 0.0005 --dropout 0.5 --epochs 1000 --n_runs 25 --results_csv experiments/Cora/PaGNN/FEATURE_NOISE0.9_SEARCH.csv

python main.py --dataset_name Texas --model FISF --feature_missing_rate 0 --feature_missing_type uniform --feature_noise_rate 0.9 --hidden_channels 128 --num_layers 2 --label_max_hops 1 --label_temperature 0.25 --lp_alpha 0.99 --goodie_lamb 1 --fisf_alpha 0.5 --fisf_beta 0.5 --fisf_gamma 50 --fisf_mask_type uniform --n_runs 25 --epochs 1000 --early_stopping True --patience 100 --disable_tqdm True --results_csv experiments/Texas/FISF/FEATURE_NOISE0.9_SEARCH.csv
python main.py --dataset_name Texas --model GCN --label_noise_type uniform --label_noise_rate 0.0 --feature_missing_type uniform --feature_missing_rate 0.0 --feature_noise_rate 0.9 --hidden_channels 128 --num_layers 2 --lr 0.01 --weight_decay 0.0005 --dropout 0.5 --epochs 1000 --n_runs 100 --results_csv experiments/Texas/GCN/FEATURE_NOISE0.9_SEARCH.csv
python main.py --dataset_name Texas --model GCNmf --label_noise_type uniform --label_noise_rate 0.0 --feature_missing_type uniform --feature_missing_rate 0.0 --feature_noise_rate 0.9 --hidden_channels 32 --num_layers 1 --lr 0.01 --weight_decay 0.0005 --dropout 0.5 --epochs 1000 --n_runs 100 --results_csv experiments/Texas/GCNmf/FEATURE_NOISE0.9_SEARCH.csv
python main.py --dataset_name Texas --model Goodie --label_noise_type uniform --label_noise_rate 0.0 --feature_missing_type uniform --feature_missing_rate 0.0 --feature_noise_rate 0.9 --hidden_channels 128 --num_layers 1 --lr 0.01 --weight_decay 0.0005 --dropout 0.5 --epochs 1000 --lp_alpha 0.9 --goodie_lamb 0.001 --n_runs 100 --results_csv experiments/Texas/Goodie/FEATURE_NOISE0.9_SEARCH.csv
python main.py --dataset_name Texas --model H2GCN --label_noise_type uniform --label_noise_rate 0.0 --feature_missing_type uniform --feature_missing_rate 0.0 --feature_noise_rate 0.9 --hidden_channels 128 --num_layers 2 --lr 0.01 --weight_decay 0.0005 --dropout 0.5 --epochs 1000 --n_runs 100 --results_csv experiments/Texas/H2GCN/FEATURE_NOISE0.9_SEARCH.csv
python main.py --dataset_name Texas --model LP --label_noise_type uniform --label_noise_rate 0.0 --feature_missing_type uniform --feature_missing_rate 0.0 --feature_noise_rate 0.9 --hidden_channels 32 --num_layers 1 --lr 0.01 --weight_decay 0.0005 --dropout 0.5 --epochs 1000 --lp_alpha_lp 0.9 --n_runs 100 --results_csv experiments/Texas/LP/FEATURE_NOISE0.9_SEARCH.csv
python main.py --dataset_name Texas --model LRGCN --label_noise_type uniform --label_noise_rate 0.0 --feature_missing_type uniform --feature_missing_rate 0.0 --feature_noise_rate 0.9 --hidden_channels 128 --num_layers 2 --lr 0.01 --weight_decay 0.0005 --dropout 0.5 --epochs 1000 --label_max_hops 1 --label_temperature 0.5 --n_runs 100 --results_csv experiments/Texas/LRGCN/FEATURE_NOISE0.9_SEARCH.csv
python main.py --dataset_name Texas --model MLP --label_noise_type uniform --label_noise_rate 0.0 --feature_missing_type uniform --feature_missing_rate 0.0 --feature_noise_rate 0.9 --hidden_channels 64 --num_layers 1 --lr 0.01 --weight_decay 0.0005 --dropout 0.5 --epochs 1000 --n_runs 100 --results_csv experiments/Texas/MLP/FEATURE_NOISE0.9_SEARCH.csv
python main.py --dataset_name Texas --model PaGNN --label_noise_type uniform --label_noise_rate 0.0 --feature_missing_type uniform --feature_missing_rate 0.0 --feature_noise_rate 0.9 --hidden_channels 128 --num_layers 1 --lr 0.01 --weight_decay 0.0005 --dropout 0.5 --epochs 1000 --n_runs 100 --results_csv experiments/Texas/PaGNN/FEATURE_NOISE0.9_SEARCH.csv
